### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by CryVeck** [LouisH-760/MusicPlayer#7]
Add keyboard shortcut for actions (volume up, down, play/pause, etc...), currently there is no shortcut.

**Comment by LouisH-760** [comment]
This can be done without touching the "GUI" interface by reusing the runnables passed at startup, since they are the same action. They aren't explicitely reserved for the actions on button, but for the symbolic action. This has to be handled by the GUI events, maybe add functions for it in the SwingGUI backend's?

**Comment by LouisH-760** [comment]
Preparing a branch & pull request for it so the issue can be closed when it gets merged, feel free to add commits to it!
